version: '3'

networks:
  net-db:
  net-proxy:

services:
  reverse_proxy:
    container_name: reverse_proxy
    build:
      context: ./reverse_proxy/
    image: reverse_proxy
    restart: always
    networks:
      - net-proxy
    ports:
      - "${APP_PORT}:${APP_PORT}"

  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./frontend/
  #     dockerfile: ./docker/Dockerfile
  #   image: frontend
  #   restart: unless-stopped
  #   networks:
  #     - net-proxy
  #   ports:
  #     - "8080:8080"
  backend:
    container_name: backend
    depends_on:
      - db
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
      target: development
    image: backend
    networks:
      - net-db
      - net-proxy
    command: npm run start:dev
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - DATABASE_URL=postgres://ft_root:admin@db:5432/transcendence
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - SESSION_SECRET=${BACKEND_SESSION_SECRET}
      - JWT_SECRET=${BACKEND_JWT_SECRET}
      - JWT_EXPIRATION=${BACKEND_JWT_EXPIRATION}
      - INTRA42_UID=${INTRA42_UID}
      - INTRA42_SECRET=${INTRA42_SECRET}
      - INTRA42_CALLBACK_URL=${INTRA42_CALLBACK_URL}
    volumes:
      - /usr/src/app
      - ./backend/src:/app/src
    restart: unless-stopped


  db:
    container_name: transcendence_db
    image: postgres:latest
    networks:
      - net-db
    volumes:
      - ./database/entrypoint/:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRESQL_TIMEZONE=${POSTGRES_TZ}
      - POSTGRESQL_LOG_TIMEZONE=${POSTGRES_TZ}
      - TZ=${POSTGRES_TZ}
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    networks:
      - net-db
    ports:
      - "4500:80"
    restart: unless-stopped
