version: '3'

networks:
  net-db:
  net-proxy:

services:
  reverse_proxy:
    container_name: transcendance_reverse_proxy
    build:
      context: ./reverse_proxy/
    image: transcendance/reverse_proxy
    restart: unless-stopped
    networks:
      - net-proxy
    depends_on:
      - backend
      - frontend
    ports:
      - "${APP_PORT}:${APP_PORT}"

  frontend:
    container_name: transcendance_frontend
    build:
      context: ./frontend/
      dockerfile: ./docker/Dockerfile
    image: transcendance/frontend:latest
    restart: unless-stopped
    networks:
      - net-proxy

  backend:
    container_name: transcendance_backend
    depends_on:
      - db
    build:
      context: ./backend/
      dockerfile: ./docker/Dockerfile
    image: transcendance/backend:latest
    networks:
      - net-db
      - net-proxy
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped

  db:
    container_name: t_db
    image: postgres:latest
    networks:
      - net-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "5432:5432"
    volumes:
      - ./database/entrypoint/:/docker-entrypoint-initdb.d
    restart: always

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    networks:
      - net-db
    ports:
      - "5050:80"
    restart: unless-stopped
